{
 "title": "build details",
 "time": { "from": "2023-05-23T15:08:42.192Z", "to": "2023-05-27T15:08:42.194Z" },
 "templating": {
  "list": [
   {
    "name": "folder",
    "label": "folder",
    "query": "SHOW TAG VALUES FROM job WITH KEY = \"owner\""
   },
   {
    "name": "job",
    "label": "Job",
    "query": "SHOW TAG VALUES FROM job WITH KEY = repo WHERE \"owner\" =~ /^($folder)$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Jenkins Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"34.125.42.68:8080\", job=\"jenkins\"}"
    }
   ]
  },
  {
   "title": "Jenkins node, queue & executor stats  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "jenkins_executor_count_value{job=\"jenkins\"}",
     "legendFormat": "Executor Count"
    },
    {
     "expr": "jenkins_node_count_value{job=\"jenkins\"}",
     "legendFormat": "Node Count"
    },
    {
     "expr": "jenkins_queue_size_value{job=\"jenkins\"}",
     "legendFormat": "Queue Size"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND (\"build_result\" = 'SUCCESS' OR \"build_result\" = 'CompletedSuccess' ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failure",
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND (\"build_result\" = 'FAILURE' OR \"build_result\" = 'CompletedError' ) AND $timeFilter "
    },
    {
     "alias": "Aborted",
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND (\"build_result\" = 'ABORTED' OR \"build_result\" = 'Aborted' ) AND $timeFilter "
    },
    {
     "alias": "Unstable",
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND (\"build_result\" = 'UNSTABLE' OR \"build_result\" = 'Unstable' ) AND $timeFilter "
    }
   ]
  },
  {
   "title": "Number of pipelines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(DISTINCT project_name) FROM jenkins_data WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Builds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Build time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select build_time/1000 FROM jenkins_data WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Build",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT build_result FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND $timeFilter  ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Build Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT \"build_exec_time\",\"project_path\",\"build_number\",\"build_causer\",\"build_time\",\"build_result\" FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$folder.*$/) AND $timeFilter "
    }
   ]
  },
  {
   "title": "Number active plugins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 1, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_active" }
   ]
  },
  {
   "title": "Number active plugins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_inactive" }
   ]
  },
  {
   "title": "Number active plugins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_inactive" }
   ]
  }
 ]
}